# Generated by Django 5.0 on 2024-03-29 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseprice",
            options={"verbose_name": "Цена курса"},
        ),
        migrations.AlterModelOptions(
            name="lessonprice",
            options={"verbose_name": "Цена урока"},
        ),
    ]
