# Generated by Django 5.0 on 2024-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("member", "member"), ("moderator", "moderator")],
                default="member",
                max_length=9,
            ),
        ),
    ]
