# Generated by Django 5.0 on 2024-03-29 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
