# Generated by Django 5.0 on 2024-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
    ]
