# Generated by Django 5.0 on 2024-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0004_remove_subscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="цена"),
        ),
    ]
