# Generated by Django 5.0 on 2024-03-29 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0005_course_price_lesson_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="price",
        ),
    ]
